apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
      annotations:
        kubernetes.io/change-cause: "Initial deployment"
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.12
        imagePullPolicy: Always
      restartPolicy: Always
  revisionHistoryLimit: 14